file_format: "1"
id: tiboard
name: tiboard
type: shield
url: https://github.com/tinyboxxx/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - tiboard_left
  - tiboard_right
